baseURL = "https://piyush-garg.github.io/"
languageCode = "en-us"
title = "Piyush Garg"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Personal website for posting some technical blogs"
  twitter = "https://twitter.com/pgarg_"
  github = "https://github.com/piyush-garg"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/home.jpeg"
  recent_posts_number = 2
